# This is a config for E2B sandbox template.
# You can use template ID (tmmtocgbxgdr4szxuuuf) or template name (vibe-kazi-test3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-kazi-test3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-kazi-test3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-kazi-test3')

team_id = "ee365870-4c65-4346-a737-64f3ed064b5b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-kazi-test3"
template_id = "tmmtocgbxgdr4szxuuuf"
